dist: trusty
language: cpp
compiler:
  - gcc
os:
  - linux
addons:
  apt:
    packages:
      - cmake
install:
  # Upgrade GCC
  - sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y
  - sudo apt-get update -qq
  - sudo apt-get install -qq g++-6
  - sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-6 60 --slave /usr/bin/g++ g++ /usr/bin/g++-6

script:
  - cmake . && make && ./test/truco-tests
